// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrbEOrcCZ7aMutfoh-g2pReUA39-Ng-M',
    appId: '1:470378363502:web:06bbad1cdff0fceba3447f',
    messagingSenderId: '470378363502',
    projectId: 'motorsporteasy',
    authDomain: 'motorsporteasy.firebaseapp.com',
    storageBucket: 'motorsporteasy.firebasestorage.app',
    measurementId: 'G-Z6XZWB2Y26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuZ6w1fYHpVFqV7oLiNoC44DXdFRr6EBA',
    appId: '1:470378363502:android:41310dc98b51b81ba3447f',
    messagingSenderId: '470378363502',
    projectId: 'motorsporteasy',
    storageBucket: 'motorsporteasy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_IKEb0czWSlec22OldxcgzwMWNq5BfwA',
    appId: '1:470378363502:ios:b89e09959bd9ef68a3447f',
    messagingSenderId: '470378363502',
    projectId: 'motorsporteasy',
    storageBucket: 'motorsporteasy.firebasestorage.app',
    iosBundleId: 'com.motorsporteasy.motorSportEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_IKEb0czWSlec22OldxcgzwMWNq5BfwA',
    appId: '1:470378363502:ios:b89e09959bd9ef68a3447f',
    messagingSenderId: '470378363502',
    projectId: 'motorsporteasy',
    storageBucket: 'motorsporteasy.firebasestorage.app',
    iosBundleId: 'com.motorsporteasy.motorSportEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrbEOrcCZ7aMutfoh-g2pReUA39-Ng-M',
    appId: '1:470378363502:web:5353215f7a5691e3a3447f',
    messagingSenderId: '470378363502',
    projectId: 'motorsporteasy',
    authDomain: 'motorsporteasy.firebaseapp.com',
    storageBucket: 'motorsporteasy.firebasestorage.app',
    measurementId: 'G-P8S2ZS1NCM',
  );

}